### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by atolstoy** [SeeLook/metronomek#1]
I can't get proper sounds from Metronomek. First, it oddly defaults to an ALSA device upon every start, regardless of my settings. But, even if I set the correct output, I get choppy sounds with trimmed fragments, just if I had  my Pulseuadio daemon configured improperly (but it's actually fine). The console output floods with the following:
`ALSA lib pcm.c:8559:(snd_pcm_recover) underrun occurred`
I tested Metronomek in Tumbleweed with Pulseaudio, and in Fedora 35 with Pipewire, but the effect was exactly the same.
I suppose you need to hunt down the problem because otherwise this great app is not usable.

**Comment by SeeLook** [comment]
Thank You a lot for using this 'great app' :-)
It was abandoned for some time and just a few days back I dusted it out, so You are just in time.
I know this issue unfortunately - Qt multimedia sucks on desktop (works just fine under Android though)
but I may say I'm on it.
I'm just porting desktop version to play through pulseaudio/pipewire directly.
Give me a few days.
I will close this issue when done, so You will know when to try it again.

Thanks for support.

.

**Comment by atolstoy** [comment]
> Give me a few days. I will close this issue when done, so You will know when to try it again.
> 
> Thanks for support.
> .

Thank you for being that kind and fast to respond! No hurry, take your time :)

**Comment by SeeLook** [comment]
Done, I think...
I'm assuming You were building Metronomek from sources, so You can pull git changes and compile it.
CMake is used now (qmake remains for Android only) and under Fedora & Suse develop packages of PulseAudio and/or ALSA are needed to compile.
When compiled against both, ALSA works only when there is no Pulse/Pipewire in the system.
So what do You think? Do we need a GUI switch to have manual choice to select ALSA if there is Pulse?

And does so simple audio app need a JACK support? (Not that mach to do, but still...)

**Comment by atolstoy** [comment]
It finally works as expected. Thanks for that!
However, I can't see anything under 'settings' now, the pane is completely empty. Was that intentional? Also, I don't know why would anyone want to  use ALSA directly. Just use 'pulse' as the default output and it will suffice.

**Comment by SeeLook** [comment]
Thanks for the report.
I'm closing this issue.

>I can't see anything under 'settings' now

Indeed, PulseAudio doesn't give much to select so drop down list is hidden...
But I believe it is temporary situation, some options will land there eventually, under Android already are.

>Also, I don't know why would anyone want to use ALSA directly.

And there are distros (KX Studio in example) which trying to keep stuff as *pulseless* as possible, preferring JACK.
So better I will leave ALSA option - all the more it is done.
But this way You answered about JACK support. :-)

Happy keeping tempo.
